<a href="https://colab.research.google.com/github/DennisDv24/BooleanAlgebraExercise/blob/master/BooleanAlgebraExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math
import matplotlib.pyplot as plt
#import tensorflow as tf

_and  = lambda x,y:   np.logical_and(x,y)
_3and = lambda x,y,z: _and(_and(x,y),z)
_or   = lambda x,y:   np.logical_or (x,y)
_3or  = lambda x,y,z: _or(_or(x,y),z)
_not  = lambda x  :   np.logical_not(x)
_xor  = lambda x,y:   np.logical_xor(x,y)
defineM = lambda d1,d2: np.zeros((d1,d2))

In [0]:
def copyArray(arrayToCopy,finalArray):
  np.copyto(finalArray,arrayToCopy, casting = 'unsafe')
  finalArray.astype(float)
 
class Sistem:

  def defFunctionAsInput():
    print('Define the output function using and, or, not, xor, 3and, 3or functions and input array x (x[0,0], x[0,1], x[1,0], x[1,1]).')
    func = Sistem.nextLogic()
    
    if func == 'and':
      Sistem.defLogicParameters('and_')
     
    if func == 'or':
      Sistem.defLogicParameters('or_')
      
    if func == 'not':
      Sistem.defLogicParameters('not_')
      
    if func == 'xor':
      Sistem.defLogicParameters('xor_')
      
  def defLogicParameters(door):
    
    if door == 'not_':
      param = input(door + 'param =')
      Sistem.conditionalToLogicParameters(param)
      
    else:
      param = (input(door + 'first param ='), input(door + 'second param ='))
      Sistem.conditionalToLogicParameters(param)
      
  def conditionalToLogicParameters(param):
    for i in range(0, len(param)):
      
      if param[i] == 'and':
        Sistem.defLogicParameters('and_')
        
      if param[i] == 'or':
        Sistem.defLogicParameters('or_')

      if param[i] == 'not':
        Sistem.defLogicParameters('not_')

      if param[i] == 'xor':
        Sistem.defLogicParameters('xor_')
        
      if param[i] == 'a' or 'b' or 'c' or 'd':
        #Function end code here
         print('donete') 
    
  def defFunction(a):
    #example function
    A = _and(a[0,0],_not(a[1,0]))
    B = _3and(a[0,1],_not(a[1,0]),_not(a[1,1]))
    C = _3and(a[0,0],_not(a[0,1]),a[1,1])
    output = _3or(A,B,C)
    #output = func  ##Funcion a partir de bucles usando valores de defFunctionAsInput
    return output
     
  def calculate(a):
    sum = 0
    for i in range(0,2):
      for j in range(0,2):
        print('=========')
        for k in range(0,2):
          for t in range(0,2):
            a[0,0] = i; a[0,1] = j
            a[1,0] = k; a[1,1] = t
            Sistem.info()
            fb[sum] = Sistem.defFunction(a) 
            sum = sum+1
          
  def nextLogic():
    func = input('Output = ')
    return func
  
  def info():
    print('input:')
    print(a)
    print('output:',Sistem.defFunction(a))
    print('-----')

In [3]:
Sistem.defFunctionAsInput()

a = defineM(2,2)  #Karnaught methode to 4 variables, [[a,b],[c,d]]
fb = np.zeros(16) #Final matrix
fbPrime = np.zeros(16)

Sistem.calculate(a)
     

fb = fb.reshape(4, 4)
fbPrime = fbPrime.reshape(4, 4)
fb = fb.transpose()
copyArray(fb, fbPrime)
print(fbPrime) #First matrix
fb[:,2], fb[:,3] = fbPrime[:,3], fbPrime[:,2]
copyArray(fb, fbPrime)
fb[3,:], fb[2,:] = fbPrime[2,:], fbPrime[3,:]
print(fb)      #Final matrix

Define the output function using and, or, not, xor, 3and, 3or functions and input array x (x[0,0], x[0,1], x[1,0], x[1,1]).
Output = and
and_first param =or
and_second param =not
or_first param =xor
or_second param =1
xor_first param =1
xor_second param =0
donete
donete
donete
donete
donete
not_param =1
donete
donete
input:
[[0. 0.]
 [0. 0.]]
output: False
-----
input:
[[0. 0.]
 [0. 1.]]
output: False
-----
input:
[[0. 0.]
 [1. 0.]]
output: False
-----
input:
[[0. 0.]
 [1. 1.]]
output: False
-----
input:
[[0. 1.]
 [0. 0.]]
output: True
-----
input:
[[0. 1.]
 [0. 1.]]
output: False
-----
input:
[[0. 1.]
 [1. 0.]]
output: False
-----
input:
[[0. 1.]
 [1. 1.]]
output: False
-----
input:
[[1. 0.]
 [0. 0.]]
output: True
-----
input:
[[1. 0.]
 [0. 1.]]
output: True
-----
input:
[[1. 0.]
 [1. 0.]]
output: False
-----
input:
[[1. 0.]
 [1. 1.]]
output: True
-----
input:
[[1. 1.]
 [0. 0.]]
output: True
-----
input:
[[1. 1.]
 [0. 1.]]
output: True
-----
input:
[[1. 1.]
 [1. 0.]]
output: False
---

In [5]:
def grayTObinary(valueTOconvert):
    valueTOconvert = int(valueTOconvert, 2)
    mask = valueTOconvert
    while mask != 0:
        mask >>= 1
        valueTOconvert ^= mask
    print('Binary array',bin(valueTOconvert)[2:])
      
    
 
valueTOconvert = input('Gray array to convert:')
grayTObinary(valueTOconvert)

Gray array to convert:11011
Binary array 10010
