<a href="https://colab.research.google.com/github/DennisDv24/BooleanAlgebraExercise/blob/master/BooleanAlgebraExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math
import matplotlib.pyplot as plt
#import tensorflow as tf

_and  = lambda x,y:   np.logical_and(x,y)
_3and = lambda x,y,z: _and(_and(x,y),z)
_or   = lambda x,y:   np.logical_or (x,y)
_3or  = lambda x,y,z: _or(_or(x,y),z)
_not  = lambda x  :   np.logical_not(x)
_xor  = lambda x,y:   np.logical_xor(x,y)
defineM = lambda d1,d2: np.zeros((d1,d2))

In [0]:
def copyArray(arrayToCopy,finalArray):
  np.copyto(finalArray,arrayToCopy, casting = 'unsafe')
  finalArray.astype(float)
  
def info():
  print('input:')
  print(a)
  print('output:',Sistem(a))
  print('-----')

In [0]:
#Elevator sistem
def Sistem(a):
  A = _and(a[0,0],_not(a[1,0]))
  B = _3and(a[0,1],_not(a[1,0]),_not(a[1,1]))
  C = _3and(a[0,0],_not(a[0,1]),a[1,1])
  output = _3or(A,B,C)
  return output

#x = defineM(4,4)
#x = [[0,1,1,1],
#     [0,0,1,1],
#     [0,0,0,1],
#     [0,0,0,0]]

a = defineM(2,2)  #Karnaught methode to 4 variables, [[a,b],[c,d]]
fb = np.zeros(16) #Final matrix
fbPrime = np.zeros(16)

sum = 0
for i in range(0,2):
  for j in range(0,2):
    print('=========')
    for k in range(0,2):
      for t in range(0,2):
        a[0,0] = i; a[0,1] = j
        a[1,0] = k; a[1,1] = t
        info()
        fb[sum] = Sistem(a) 
        sum = sum+1
     

fb = fb.reshape(4, 4)
fbPrime = fbPrime.reshape(4, 4)
fb = fb.transpose()
copyArray(fb, fbPrime)
print(fbPrime) #First matrix
fb[:,2], fb[:,3] = fbPrime[:,3], fbPrime[:,2]
copyArray(fb, fbPrime)
fb[3,:], fb[2,:] = fbPrime[2,:], fbPrime[3,:]
print(fb)      #Final matrix

input:
[[0. 0.]
 [0. 0.]]
output: False
-----
input:
[[0. 0.]
 [0. 1.]]
output: False
-----
input:
[[0. 0.]
 [1. 0.]]
output: False
-----
input:
[[0. 0.]
 [1. 1.]]
output: False
-----
input:
[[0. 1.]
 [0. 0.]]
output: True
-----
input:
[[0. 1.]
 [0. 1.]]
output: False
-----
input:
[[0. 1.]
 [1. 0.]]
output: False
-----
input:
[[0. 1.]
 [1. 1.]]
output: False
-----
input:
[[1. 0.]
 [0. 0.]]
output: True
-----
input:
[[1. 0.]
 [0. 1.]]
output: True
-----
input:
[[1. 0.]
 [1. 0.]]
output: False
-----
input:
[[1. 0.]
 [1. 1.]]
output: True
-----
input:
[[1. 1.]
 [0. 0.]]
output: True
-----
input:
[[1. 1.]
 [0. 1.]]
output: True
-----
input:
[[1. 1.]
 [1. 0.]]
output: False
-----
input:
[[1. 1.]
 [1. 1.]]
output: False
-----
[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
